# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  #config.vm.box = "Sliim/kali-linux-1.1.0-amd64"
  config.vm.box = "Sliim/kali-linux-2.0-amd64"

  config.ssh.private_key_path = '.ssh/pentest-env'
  config.ssh.username =  'root'

  config.vm.network "forwarded_port", guest: 80, host: 8000
  config.vm.network "forwarded_port", guest: 443, host: 8443

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook_vagrant.yml"
  end

end
